import type { Course } from './course.schema'
import { SCHEMA_VERSION } from './course.schema'

/** Curso de ejemplo (mínimo viable) usado al arrancar sin importar nada. */
export const sampleCourse: Course = {
  schema_version: SCHEMA_VERSION,
  course: {
    id: 'curso-prl-basico',
    title: 'Prevención de Riesgos Laborales · Nivel Básico',
    subtitle: 'Edición demo',
    description: 'Curso de ejemplo generado para validar la carcasa SCORM.',
    authoring_entity: 'Mecohisa',
    source_document: 'manual_prl_basico.pdf',
    estimated_hours: 4,
    language: 'es',
  },
  scorm: {
    version: '1.2',
    identifier: 'SCORMEDITOR-PRL-BASICO',
    title: 'PRL Nivel Básico',
    mastery_score: 60,
    rules: {
      min_required_screens_pct: 100,
      require_interactions: true,
      min_score: 60,
      attempts_allowed: 0,
      score_source: 'final_test',
      navigation: 'mixed',
      allow_resume: true,
    },
  },
  shell: {
    brand: 'Mecohisa Formación',
    primary_color: '#0b5fff',
    show_sidebar: true,
    show_progress: true,
    language: 'es',
  },
  modules: [
    {
      id: 'm1',
      title: 'Módulo 1 · Conceptos básicos',
      units: [
        {
          id: 'u1',
          title: 'Unidad 1 · Marco normativo',
          summary: 'Repaso de la Ley 31/1995 y conceptos fundamentales de PRL.',
          status: 'ok',
          screens: [
            {
              id: 's-cover',
              type: 'cover',
              title: 'PRL · Nivel Básico',
              objective: '',
              student_text: 'Bienvenido/a al curso. Pulsa **Siguiente** para comenzar.',
              source_refs: [],
              visual_resource: { kind: 'none', src: '', alt: '', tracks: [], has_voice: false, layout: 'top', media_width: '50' },
              interaction: null,
              required: false,
              min_time_seconds: 0,
              audio_src: '',
              transcript: '',
              accessibility: { alt_text_ok: true, keyboard_ok: true, contrast_ok: true },
              scorm: { counts_for_completion: false },
              editor_notes: [],
              status: 'ok',
            },
            {
              id: 's-obj',
              type: 'objectives',
              title: 'Objetivos de la unidad',
              objective: 'Conocer el marco normativo de la PRL.',
              student_text:
                'Al finalizar serás capaz de:\n- Identificar la normativa básica.\n- Reconocer derechos y deberes.',
              source_refs: [{ doc: 'manual_prl_basico.pdf', locator: 'p.12' }],
              visual_resource: { kind: 'none', src: '', alt: '', tracks: [], has_voice: false, layout: 'top', media_width: '50' },
              interaction: null,
              required: true,
              min_time_seconds: 10,
              audio_src: '',
              transcript: '',
              accessibility: { alt_text_ok: true, keyboard_ok: true, contrast_ok: true },
              scorm: { counts_for_completion: true },
              editor_notes: [],
              status: 'ok',
            },
            {
              id: 's-content',
              type: 'content',
              title: 'La Ley 31/1995',
              objective: 'Conocer la finalidad de la ley.',
              student_text:
                'La Ley de Prevención de Riesgos Laborales establece el marco para proteger la seguridad y salud de los trabajadores.',
              source_refs: [{ doc: 'manual_prl_basico.pdf', locator: 'p.14', transform: 'resumen' }],
              visual_resource: { kind: 'none', src: '', alt: '', tracks: [], has_voice: false, layout: 'top', media_width: '50' },
              interaction: {
                id: 'i-acc-1',
                type: 'accordion',
                prompt: 'Principios de la acción preventiva',
                instructions: 'Despliega cada principio para leer su descripción.',
                options: [],
                config: {
                  items: [
                    { title: 'Evitar los riesgos', body: 'Eliminar el riesgo en origen siempre que sea posible.' },
                    { title: 'Evaluar los inevitables', body: 'Valorar los riesgos que no pueden evitarse.' },
                  ],
                },
                feedback: { correct: '', incorrect: '', explanation: 'Art. 15 de la Ley 31/1995.' },
                scored: false,
                points: 0,
                attempts: 1,
                retries: 0,
                learning_objective: 'Conocer los principios de la acción preventiva',
                source_refs: [{ doc: 'manual_prl_basico.pdf', locator: 'art.15' }],
              },
              required: true,
              min_time_seconds: 20,
              audio_src: '',
              transcript: '',
              accessibility: { alt_text_ok: true, keyboard_ok: true, contrast_ok: true },
              scorm: { counts_for_completion: true },
              editor_notes: [],
              status: 'ok',
            },
            {
              id: 's-quiz',
              type: 'unit_quiz',
              title: 'Comprueba lo aprendido',
              objective: 'Autoevaluación de la unidad.',
              student_text: 'Responde para verificar tu comprensión.',
              source_refs: [],
              visual_resource: { kind: 'none', src: '', alt: '', tracks: [], has_voice: false, layout: 'top', media_width: '50' },
              interaction: {
                id: 'i-sc-1',
                type: 'single_choice',
                prompt: '¿Qué ley regula la PRL en España?',
                instructions: 'Selecciona una opción.',
                options: [
                  { id: 'a', text: 'Ley 31/1995', correct: true },
                  { id: 'b', text: 'Ley 7/2007', correct: false },
                  { id: 'c', text: 'Ley 40/2015', correct: false },
                ],
                config: {},
                feedback: {
                  correct: '¡Correcto! La Ley 31/1995.',
                  incorrect: 'No es correcto, repasa el marco normativo.',
                  explanation: 'La Ley 31/1995 es la norma de referencia en PRL.',
                },
                scored: true,
                points: 1,
                attempts: 1,
                retries: 2,
                learning_objective: 'Identificar la normativa básica',
                source_refs: [{ doc: 'manual_prl_basico.pdf', locator: 'p.14' }],
              },
              required: true,
              min_time_seconds: 0,
              audio_src: '',
              transcript: '',
              accessibility: { alt_text_ok: true, keyboard_ok: true, contrast_ok: true },
              scorm: { counts_for_completion: true },
              editor_notes: [],
              status: 'ok',
            },
            {
              id: 's-summary',
              type: 'summary',
              title: 'Resumen de la unidad',
              objective: '',
              student_text: 'Has repasado el marco normativo básico de la PRL.',
              source_refs: [],
              visual_resource: { kind: 'none', src: '', alt: '', tracks: [], has_voice: false, layout: 'top', media_width: '50' },
              interaction: null,
              required: true,
              min_time_seconds: 10,
              audio_src: '',
              transcript: '',
              accessibility: { alt_text_ok: true, keyboard_ok: true, contrast_ok: true },
              scorm: { counts_for_completion: true },
              editor_notes: [],
              status: 'ok',
            },
          ],
        },
      ],
    },
  ],
  assessments: {
    unit_tests: [],
    final_test: {
      id: 'final',
      unit_id: '',
      title: 'Test final',
      pass_score: 60,
      questions: [
        {
          id: 'q1',
          prompt: '¿La Ley 31/1995 protege la seguridad y salud de los trabajadores?',
          type: 'true_false',
          options: [
            { id: 't', text: 'Verdadero', correct: true },
            { id: 'f', text: 'Falso', correct: false },
          ],
          feedback: { correct: 'Correcto.', incorrect: 'Incorrecto.', explanation: 'Es su finalidad principal.' },
          points: 1,
          learning_objective: 'Conocer la finalidad de la ley',
          source_refs: [{ doc: 'manual_prl_basico.pdf', locator: 'p.14' }],
        },
      ],
    },
  },
  glossary: [
    { term: 'Riesgo laboral', definition: 'Posibilidad de que un trabajador sufra un daño derivado del trabajo.', source_refs: [] },
  ],
  bibliography: [{ ref: 'Ley 31/1995, de 8 de noviembre, de Prevención de Riesgos Laborales.' }],
  quality_checklist: {},
}
